### ISSUE TITLE
Bug - Saving error when 1-gram or 2-gram do not tags

### ISSUE THREAD

**Issue by sarahlukens** [usnistgov/nestor-tmp2#60]
Version: 0.3dev0.r28, 
Error: nestor will crash in certain cases after clicking "UPDATE TAG EXTRACTION"

Steps to reproduce:
- Create new nestor project
- Leave some tagging element empty (such as Single word analysis or Multi word analysis)
- Will get save messages up to "Empty Docs:" ... "Docs must have at most xy tokens (xyth percentile)", then crashes python

Error message:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nestor/ui/taggingUI_app.py", line 1510, in onClick_saveTrack
    self.completenessPlot.plot_it(nbins)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/nestor/ui/taggingUI_app.py", line 2267, in plot_it
    color='xkcd:slate')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/seaborn/distributions.py", line 231, in distplot
    kdeplot(a, vertical=vertical, ax=ax, color=kde_color, **kde_kws)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/seaborn/distributions.py", line 294, in _univariate_kdeplot
    x, y = _scipy_univariate_kde(data, bw, gridsize, cut, clip)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/seaborn/distributions.py", line 366, in _scipy_univariate_kde
    kde = stats.gaussian_kde(data, bw_method=bw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/kde.py", line 172, in __init__
    self.set_bandwidth(bw_method=bw_method)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/kde.py", line 499, in set_bandwidth
    self._compute_covariance()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/stats/kde.py", line 510, in _compute_covariance
    self._data_inv_cov = linalg.inv(self._data_covariance)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scipy/linalg/basic.py", line 975, in inv
    raise LinAlgError("singular matrix")
numpy.linalg.linalg.LinAlgError: singular matrix
Abort trap: 6

**Comment by rtbs-dev** [comment]
Having difficulty reproducing this. 

leaving either tab completely empty and both
1. `File>Save Project` or
2. `Report>Update Tag Extraction`

are working fine for me. However, this could be related to #56  , since the KDE code is flagging. I think I'll remove KDE plotting, since there is already some code for getting nicely binned histograms in there (I don't think the KDE is really adding much?)

**Comment by rtbs-dev** [comment]
Should be fixed with  35b11c9 on master. Can you update and report back?

**Comment by rtbs-dev** [comment]
For now, since the KDE has been removed, I'm going to go ahead and close this. Feel free to comment if something else related to this goes wrong, I'll be happy to re-open.
